// Barashada vidiyooyinka — Learning video data bank

export type VideoLevel = 'beginner' | 'intermediate' | 'advanced'

export interface LearningVideo {
  id: number
  title: string
  creator: string
  views: string
  level: VideoLevel
  tiktokUrl: string | null
  thumbnailColor: string
  emoji: string
  category: string
}

export const learningVideos: LearningVideo[] = [
  {
    id: 1,
    title: 'Daily routine phrases',
    creator: '@englishwithali',
    views: '1.2M',
    level: 'beginner',
    tiktokUrl: null,
    thumbnailColor: '#8B5CF6',
    emoji: '☀️',
    category: 'Daily Life',
  },
  {
    id: 2,
    title: '10 phrases you use every day',
    creator: '@bbclearnenglish',
    views: '890K',
    level: 'beginner',
    tiktokUrl: null,
    thumbnailColor: '#3B82F6',
    emoji: '💬',
    category: 'Speaking',
  },
  {
    id: 3,
    title: 'How to disagree politely',
    creator: '@englishtips',
    views: '2.1M',
    level: 'intermediate',
    tiktokUrl: null,
    thumbnailColor: '#EF9F27',
    emoji: '🤝',
    category: 'Communication',
  },
  {
    id: 4,
    title: 'Greetings & small talk',
    creator: '@orionenglish',
    views: '340K',
    level: 'beginner',
    tiktokUrl: null,
    thumbnailColor: '#EC4899',
    emoji: '👋',
    category: 'Greetings',
  },
  {
    id: 5,
    title: 'Phrasal verbs at work',
    creator: '@businessenglish',
    views: '1.5M',
    level: 'intermediate',
    tiktokUrl: null,
    thumbnailColor: '#6366F1',
    emoji: '💼',
    category: 'Career',
  },
  {
    id: 6,
    title: 'How to write a professional email',
    creator: '@writingcoach',
    views: '3.2M',
    level: 'intermediate',
    tiktokUrl: null,
    thumbnailColor: '#0EA5E9',
    emoji: '✉️',
    category: 'Writing',
  },
  {
    id: 7,
    title: 'Advanced idioms explained',
    creator: '@idiommaster',
    views: '760K',
    level: 'advanced',
    tiktokUrl: null,
    thumbnailColor: '#7C3AED',
    emoji: '🧠',
    category: 'Vocabulary',
  },
  {
    id: 8,
    title: 'Numbers, dates & time',
    creator: '@englishwithali',
    views: '2.8M',
    level: 'beginner',
    tiktokUrl: null,
    thumbnailColor: '#F59E0B',
    emoji: '🔢',
    category: 'Basics',
  },
  {
    id: 9,
    title: 'Conditionals made easy',
    creator: '@grammarfix',
    views: '1.1M',
    level: 'intermediate',
    tiktokUrl: null,
    thumbnailColor: '#10B981',
    emoji: '📐',
    category: 'Grammar',
  },
  {
    id: 10,
    title: 'Academic writing vocabulary',
    creator: '@studyenglish',
    views: '430K',
    level: 'advanced',
    tiktokUrl: null,
    thumbnailColor: '#DC2626',
    emoji: '📝',
    category: 'Academic',
  },
  {
    id: 11,
    title: 'Pronunciation: TH sounds',
    creator: '@soundright',
    views: '5.3M',
    level: 'beginner',
    tiktokUrl: null,
    thumbnailColor: '#059669',
    emoji: '👄',
    category: 'Pronunciation',
  },
  {
    id: 12,
    title: 'How to give opinions confidently',
    creator: '@speakup',
    views: '920K',
    level: 'intermediate',
    tiktokUrl: null,
    thumbnailColor: '#D97706',
    emoji: '💡',
    category: 'Speaking',
  },
  {
    id: 13,
    title: 'Debate & persuasion language',
    creator: '@advancedenglish',
    views: '210K',
    level: 'advanced',
    tiktokUrl: null,
    thumbnailColor: '#4F46E5',
    emoji: '⚖️',
    category: 'Debate',
  },
  {
    id: 14,
    title: 'Food & restaurant vocabulary',
    creator: '@englisheats',
    views: '1.7M',
    level: 'beginner',
    tiktokUrl: null,
    thumbnailColor: '#EA580C',
    emoji: '🍽️',
    category: 'Daily Life',
  },
  {
    id: 15,
    title: 'Nuance: almost vs nearly vs barely',
    creator: '@wordnerds',
    views: '380K',
    level: 'advanced',
    tiktokUrl: null,
    thumbnailColor: '#0F766E',
    emoji: '🎯',
    category: 'Vocabulary',
  },
]
